TjSnow.Web/Controllers/HeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TjSnow.Application.Services.Category;
using TjSnow.DTO.Category;
using TjSnow.Web.Models;

namespace TjSnow.Web.Controllers
{
    public class HeaderController : Controller
    {
        private const int FastShipCategoryId = -5;

        private readonly ICategoryService _categoryService;
        public HeaderController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        
        public PartialViewResult HeaderCategory()
        {
            FrontViewModel model = new FrontViewModel();
            var categories = _categoryService.RetrieveCategories().ToList();

            categories.Add(new CategoryShortDTO
            {
                Id = FastShipCategoryId,
                Name = "Fast Ship"
            });

            model.categories = categories;

            return PartialView("~/Views/Header/HeaderSelectCategory.cshtml", model);
        }
	}
}

TjSnow.Web/Views/Shared/Dashboard.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard</title>

    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/cssAdmin")
    <link href="~/Content/dashboard.css" rel="stylesheet">
    <link href="~/Content/results.css" rel="stylesheet">
    <link href="~/Content/addmachine.css" rel="stylesheet" />
    <link href="~/Content/machineedit.css" rel="stylesheet" />
    <link href="~/Content/datatables.bootstrap.css" rel="stylesheet" />
    <base href="/">
</head>
<body>
    <div ng-class="{'container' : location.path() != '/admin/grid-view', 'full-width' : location.path() == '/admin/grid-view'}" ng-app="TjSnow" keypress-events>

        <div class="header clearfix">
		<!-- <div class="pull-right user-info">@ViewBag.Username <a href="/admin/password/reset?userId=1&code=code">Reset Password</a> / <a href="@Url.Action("Logout", "Account")">Log out</a></div> -->
		<div class="pull-right user-info">@ViewBag.Username / <a href="@Url.Action("Logout", "Account")">Log Out</a></div>
            <h3><a href="https://usedspotwelder.com/"><img class="admin-logo" src="~/Content/images/form-signin_logo2.png"></a></h3>
        </div>

        @*<ol class="breadcrumb">
                <li><a href="#">Dashboard</a></li>
                <li class="active">Data</li>
                <li class="pull-right">
                    <a href="#" class="add-machine">Add machine</a>
                </li>
            </ol>*@

        <div ng-view=""></div>

        <footer class="footer" ng-if="location.path() != '/admin/grid-view'">
            <p>&copy; T. J. Snow Co</p>
        </footer>

    </div> <!-- /container -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/app")

</body>
</html>

TjSnow.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=0.8"/>
    <title>@(String.IsNullOrEmpty(ViewBag.Title) ? "T.J. Snow" : ViewBag.Title)</title>
    <meta name="description" content="@(ViewBag.MetaDescription ?? string.Empty)"/>
    <meta name="format-detection" content="telephone=no" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600italic,600,700,700italic,800,800italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'/>
    <link href="https://fonts.googleapis.com/css?family=Open Sans" rel="stylesheet"> 
    <!--BELOW LINE FOR HOME STYLE. REMOVE IF NEEDED -->
    <!--<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">-->
    <link rel="shortcut icon" href="favicon.ico"/>



    @Styles.Render("~/Content/css/Front")
    @Scripts.Render("~/bundles/front")

    @Scripts.Render("~/bundles/bootstrap")
    <base href="/"/>

    <script type="text/javascript">
        $(document).ready(function() {
            $('.popup .return, .overlay').click(function() {
                $('.popup, .overlay').css('opacity', '0');
                $('.popup, .overlay').css('visibility', 'hidden');
            });
            $('a.open_window').click(function(e) {
                $('.popup, .overlay').css('opacity', '1');
                $('.popup, .overlay').css('visibility', 'visible');
                e.preventDefault();
            });
        });
    </script>
    <script>

        $(window).resize(function() {
            $(function() {
                if (window.screen.width > 480) {
                    console.log('destroy');
                    jQuery('.d-carousel .carousel').jcarousel('destroy');

                } else {
                    jQuery('.d-carousel .carousel').jcarousel({
                        scroll: 1,
                        //vertical: true,
                        //auto:1,
                        //wrap: 'both' //возврат в начало
                        //wrap: 'circular' //по кругу
                    });
                }
            })

        })

        $(function() {
            var pull2 = $('#pull2');
            menu_mobile = $('.menu .menu_wrap');
            menu_mobileHeight = menu_mobile.height();
            $(pull2).on('click', function(e) {
                e.preventDefault();
                menu_mobile.slideToggle();
            });
        });
        if (window.screen.width < 480) {
            $(document).ready(function() {
                jQuery('.d-carousel .carousel').jcarousel({
                    scroll: 1,
                    //vertical: true,
                    //auto:1,
                    //wrap: 'both' //возврат в начало
                    //wrap: 'circular' //по кругу
                });

                window.onload = function() {
                    var maxHeight = 0;
                    $(".carousel > li").each(function() {
                        var h_block = parseInt($(this).height());
                        if (h_block > maxHeight) {
                            maxHeight = h_block;
                        };
                    });
                    $(".carousel > li").height(maxHeight);
                }

            });

        }
    </script>
    @Html.Raw(File.ReadAllText(Server.MapPath("~/Content/TrackingCodeHeader.html")))
</head>
<body>
<div class="wraper">
    <div>
        <div class="top">
            <a href="https://tjsnow.com/welding-machinery/" class="logo">
                <img src="/Content/images/logo.jpg" width="369" height="104" alt=""/>
            </a>
            <div class="info">
               <!-- <div class="info_top">
                    <div class="search_text">
                        <p class="text-invisible"><span>Search Inventory!</span></p>
                        <p style="display: none" class="text-visible"><span>Search Now!</span></p>
                        <p>Your #1 Source For New & Used Resistance Welding Equipment</p>
                    </div>
                    <div class="phone">
                        <p><span>800-NOW-SNOW</span></p>
                        <p>CONTACT US NOW!</p>
                    </div>
	       </div>-->
                <div class="search">
                    <div class="search_hidden">
                        <input type="text" placeholder="Category, Product ID, Keyword" id="search_keyword_input_header"/>
                        @*<script>                 

                            if ($(window).width() < 480) {
                                    $("#search_keyword_input_header").attr('placeholder', 'Search');
                                }
                        </script>*@
                        <button id="search_keyword_button_header"><img src="/Content/images/icons/1.png" width="14" height="14" alt=""/></button>
                    </div>

                </div>
                @{Html.RenderAction("HeaderCategory", "Header");}
            </div>
        </div>
        <div class="menu">
            <button id="pull2">Menu<span><img src="/Content/images/icons/6.jpg" width="37" height="37" alt="" /></span></button>
            <ul class="menu_wrap">
                <li><a href="https://usedspotwelder.com">Home</a></li>
                <li><a href="http://www.tjsnow.com/about-us/">About</a></li>
                <li><a href="http://www.tjsnow.com/machines/">Welders</a></li>
                <li><a href="http://www.tjsnow.com/resistance-welding-supplies/">Supplies</a></li>
                <li><a href="http://www.tjsnow.com/service/">Service</a></li>
                <li><a href="http://www.tjsnow.com/seminars/">Training</a></li>
                <li><a href="http://tjsnow.com/contact/">Contact Us</a></li>
		            </ul>
        </div>
        @RenderBody()
        <div id="modal-container" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-content" id="modalcontent">
            </div>
        </div>

        <script type="text/javascript">
            $(function() {

                $('body').on('click', '.modal-link', function(e) {
                    e.preventDefault();
                    $(this).attr('data-target', '#modal-container');
                    $(this).attr('data-toggle', 'modal');
                });

                $('body').on('click', '.modal-close-btn', function() {
                    $('#modal-container').modal('hide');
                });

                $('#modal-container').on('hidden.bs.modal', function() {
                    $(this).removeData('bs.modal');
                });

                $('#CancelModal').on('click', function() {
                    return false;
                });
            });
        </script>

        <div class="copy">
            <p class="text-invisible">Contents Copyright 1998 - @DateTime.Now.Year, T. J. Snow, Co. All Rights Reserved </p>
            <div style="display: none" class="text-visible footer-links"><a class="footer-link" href="http://www.tjsnow.com/terms-and-conditions/">TERMS AND CONDITIONS</a> | <a class="footer-link" href="http://www.tjsnow.com/contact-us/">CONTACT</a>
            </div>
        </div>
        <div class="footer">
            <div class="footer_left">
                <p class="text-invisible">
                    <span>T. J. Snow, Company</span> is an industry-leading manufacturer and supplier
                    of new and used spot welders, welder controls , and seam weld heads,
                    transformers, parts and supplies. <a href="http://www.tjsnow.com/about-us/">Learn more »</a>
                </p>
                <p style="display: none" class="text-visible">
                    Contents Copyright 1998 - @DateTime.Now.Year, T. J. Snow, Co. All Rights Reserved<br/>
                    120 Nowlin Lane, Chattanooga, TN 37421 | <a href="#">welders@tjsnow.com</a><br/><br/>
                    <span>T. J. Snow, Company</span> is an industry-leading manufacturer and<br/>
                    supplier of new and used spot welders, welder controls,<br/> and seam weld heads, transformers, parts<br/> and supplies. <a href="http://www.tjsnow.com/about-us/">Learn more »</a>
                </p>
            </div>
            <div class="footer_right text-invisible">
                <ul class="menu_wrap">
                    <li><a href="http://www.tjsnow.com/terms-and-conditions/">TERMS AND CONDITIONS</a></li>
                    <li><a href="http://www.tjsnow.com/contact-us/">CONTACT</a></li>
                </ul>
                <p class="text-invisible">120 Nowlin Lane, Chattanooga, TN 37421 | <a href="#">welders@tjsnow.com</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="overlay" title="window"></div>
<div class="popup">
    <h2>Thank You!</h2>
    <p>We appreciate your interest in a T.J. Snow used equipment item.<br/>
        An Application Engineer will review your request and will follow up<br/>
        with you as soon as possible. If you need immediate assistance please<br/>
        call our main office at (423) 894-6234.
    </p>
    <a id="goBackLink" href class="return">Return To Site</a>
    <script>
        var link = document.getElementById("goBackLink");
        link.setAttribute('href', location);
    </script>
</div>
@Html.Raw(File.ReadAllText(Server.MapPath("~/Content/TrackingCodeFooter.html")))
</body>


@RenderSection("scripts", required: false)
</html>

TjSnow.Web/Views/Shared/_LayoutLoginAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>T.J. Snow</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,700,300,600,800,400&subset=latin,cyrillic-ext,latin-ext,cyrillic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700,300italic&subset=latin,cyrillic-ext,latin-ext,cyrillic' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="favicon.ico">

    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/cssAdmin")
    @Scripts.Render("~/bundles/modernizr")
    <base href="/">
</head>
<body ng-app="TjSnowFront">

    <div class="page-wrapper container">



        <!-- CONTENT
        =================================-->
        @RenderBody()
        <!-- /CONTENT ============-->
    </div>

    <div id="footer">
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")

    @RenderSection("scripts", required: false)

</body>
</html>